<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <OutputType Condition="!Exists('$(MSBuildProjectDirectory)\App.xaml')">Library</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Assets\Xb31Control.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Xb31.Core\Xb31.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\Xb31Control.ico" />
  </ItemGroup>
</Project>
