<Project>
  <PropertyGroup>
    <Authors>ryancooper73</Authors>
    <Copyright>Copyright (c) 2026 ryancooper73</Copyright>
    <PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/ryancooper73/srs-xb31-windows-control</RepositoryUrl>
  </PropertyGroup>
</Project>
